### ISSUE TITLE
Gestione Router-Vue

### ISSUE THREAD

**Issue by Ele-nonsochi** [Vinc-78/DeliveBoo#18]
Compilazione file router.js e modifica view.js . Inizio Sezione Home

**Comment by Vinc-78** [comment]
Istallato router -vue , risolto conflitto di versione disistallando la versione 4.6 di router-vue e istallando la 3.5.3 compatibile con Vue 2.5 
Crete le rotte e e il file roter.js per la gestione dei componenti
